
DROP TABLE IF EXISTS `key1234`;

CREATE TABLE `key1234` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tag` varchar(32) NOT NULL DEFAULT '',
  `payload` json DEFAULT NULL,
  PRIMARY KEY (`id`)
) 
COLLATE='utf8_general_ci' 
ENGINE=InnoDB DEFAULT CHARSET=utf8;